### ISSUE TITLE
Autoupdate on packagist.org

### ISSUE THREAD

**Issue by lsolesen** [ole1986/pdf-php#10]
The package is available to installation through ´composer´ on packagist.org. It can auto-update on each commit and on each tag. We need to make sure that it is setup correctly. See the explanation from packagist.org below:

### GitHub Service Hook

Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub. To do so you can go to your GitHub repository, click the "Settings" button, then "Webhooks & Services". Add a "Packagist" service, and configure it with your API token, plus your Packagist username. Check the "Active" box and submit the form. You can then hit the "Test Service" button to trigger it and check if Packagist removes the warning about the package not being auto-updated. (From: https://packagist.org/about#how-to-update-packages)

**Comment by ole1986** [comment]
Please provide me with the API token and username

**Comment by lsolesen** [comment]
Anywhere I can pm you that?

Den tor. 12. maj 2016 08.55 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
through email: ole.k at web.de

**Comment by lsolesen** [comment]
Information sent on e-mail to you.

**Comment by ole1986** [comment]
Packagist service settings applied. Can you confirm from the other side?

**Comment by lsolesen** [comment]
Confirmed: https://packagist.org/packages/randos/pdf-php
