### ISSUE TITLE
Protect the master branch - only possible to merge pull requests when Travis succeeds and no forced pushes

### ISSUE THREAD

**Issue by lsolesen** [ole1986/pdf-php#2]
Could you please grant me admin rights to this repository so I can access settings?

**Comment by ole1986** [comment]
I cant do this without transfering it completely

**Comment by lsolesen** [comment]
Ok. That is probably because it is a personal repo and not an organization then. What I think you should do is under `settings/branches` is to protect the `master` branch and only allow merges when Travis tests passes. That way it will be possible to make sure that pull requests are adhering to coding standards or possible unit tests.

**Comment by ole1986** [comment]
Ok - master branch is protected and travis is set to automatically check on pull request

**Comment by lsolesen** [comment]
We need to figure this one out: https://github.com/ole1986/pdf-php/issues/7
