### ISSUE TITLE
Figure out why pushes are disabled on TravisCI

### ISSUE THREAD

**Issue by lsolesen** [ole1986/pdf-php#7]
@ole1986 Did you disable anything on Travis, that would cause pushes to be disabled in the last two requests? https://travis-ci.org/ole1986/pdf-php/requests

**Comment by ole1986** [comment]
Tello me, should I disable or enable it? please be more specific and do not open issues for every single thing please....

**Comment by lsolesen** [comment]
Usually I just enable Travis support from the Travis interface, add the
.travis.yml to the repository and then it works. I've haven't seen pushes
disabled before.

I've open new issues so the single issue does not get to confusing with
several discussions going on. Sorry about that. To me it seemed easier
because then we could close stuff quicker, I thought.

Den tir. 10. maj 2016 22.00 skrev ole <notifications@github.com>:

**Comment by ole1986** [comment]
Well, I have no idea why it isnt working... Lets wait 24h... maybe there is a reset

**Comment by lsolesen** [comment]
It seems to work now: https://travis-ci.org/ole1986/pdf-php/requests, so closing this!
